
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION COLOR KIND NUMBER SIZEexpression : actionRule\n\t\t\t\t  | mainRulemainRule :  NUMBER SIZE COLOR KINDactionRule :  ACTION'
    
_lr_action_items = {'ACTION':([0,],[4,]),'NUMBER':([0,],[5,]),'$end':([1,2,3,4,8,],[0,-1,-2,-4,-3,]),'SIZE':([5,],[6,]),'COLOR':([6,],[7,]),'KIND':([7,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'actionRule':([0,],[2,]),'mainRule':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> actionRule','expression',1,'p_expression','main.py',45),
  ('expression -> mainRule','expression',1,'p_expression','main.py',46),
  ('mainRule -> NUMBER SIZE COLOR KIND','mainRule',4,'p_mainRule','main.py',49),
  ('actionRule -> ACTION','actionRule',1,'p_actionRule','main.py',53),
]
